### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by TobiasHuber1980** [enbility/eebus-go#60]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x1bbfab4]

goroutine 1 [running]:
github.com/evcc-io/evcc/core.(*Loadpoint).Prepare(0x4c35900, 0x57879c0, 0x5787a00, 0x4ce4380)
	/home/runner/work/evcc/evcc/core/loadpoint.go:609 +0x93c
github.com/evcc-io/evcc/core.(*Site).Prepare(0x571fd40, 0x4c6d900, 0x4f14200)
	/home/runner/work/evcc/evcc/core/site.go:766 +0xd8
github.com/evcc-io/evcc/cmd.runRoot(0x3ae9398, {0x3b222b8, 0x0, 0x0})
	/home/runner/work/evcc/evcc/cmd/root.go:260 +0x179c
github.com/spf13/cobra.(*Command).execute(0x3ae9398, {0x4c0e148, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x714
github.com/spf13/cobra.(*Command).ExecuteC(0x3ae9398)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x418
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/evcc-io/evcc/cmd.Execute()
	/home/runner/work/evcc/evcc/cmd/root.go:109 +0x20
main.main()
	/home/runner/work/evcc/evcc/main.go:44 +0x3c
```

config:
```meters:
- type: template
  template: rct-power 
  usage: grid  
  host: 192.168.178.10  
  name: grid1
- type: template
  template: rct-power 
  usage: pv  
  host: 192.168.178.10  
  name: pv2
- type: template
  template: rct-power 
  usage: battery  
  host: 192.168.178.10  
  name: battery3

chargers:
- type: template
  template: hardybarth-salia 
  host: 192.168.178.11  
  name: wallbox4

loadpoints:
- title: Garage
  charger: wallbox4
  mode: pv
  phases: 3
  mincurrent: 6
  maxcurrent: 16
  resetOnDisconnect: false

site:
  title: Zuhause
  meters:
    grid: grid1
    pv:
    - pv2
    battery:
    - battery3
```

**Comment by DerAndereAndi** [comment]
Hallo, ich denke du hast dich wohl im Repository vertan. Dein Problem hat nichts mit EEBUS zu tun sondern mit evcc selbst. Das passende Repository ist hier: https://github.com/evcc-io/evcc
